-- Creating Datawarehouse star schema

select * from staging.stg_vgsales_clean;

create schema if not exists dw;

-- 1) Dimensions (lookup)
create table if not exists dw.dim_platform(
	platform_id int generated by default as identity primary key,
	platform text not null unique,
	created_at timestamp not null default current_timestamp
	
);

create table if not exists dw.dim_genre(
	genre_id int generated by default as identity primary key,
	genre text not null unique,
	created_at timestamp not null default current_timestamp
);

create table if not exists dw.dim_publisher(
	publisher_id int generated by default as identity primary key,
	publisher text not null unique,
	created_at timestamp not null default current_timestamp
);

-- 2) Game dimension (main dimension)
-- Grain: 1 row per name, platform and year

create table if not exists dw.dim_game(
	game_id int generated by default as identity primary key,
	game text not null,
	year int null,
	year_key int generated always as (coalesce(year,-1)) stored,
	rank int null,
	
	platform_id int not null,
	genre_id int not null,
	publisher_id int not null,
	
	created_at timestamp not null default current_timestamp,
	
	constraint fk_game_platform
		foreign key (platform_id) references dw.dim_platform(platform_id)
		on update cascade on delete restrict,
		
	constraint fk_game_genre
		foreign key (genre_id) references dw.dim_genre(genre_id)
		on update cascade on delete restrict,
	
	constraint fk_game_publisher
		foreign key (publisher_id) references dw.dim_publisher(publisher_id)
		on update cascade on delete restrict,
		
	constraint uq_game_grain unique (game, platform_id, year_key)
);

-- 3) Fact table

create table if not exists dw.fact_sales(

	game_id int primary key,
	na_sales numeric(10,2) null,
	eu_sales numeric(10,2) null,
	jp_sales numeric(10,2) null,
	other_sales numeric(10,2) null,
	global_sales numeric(10,2) null,
	
	created_at timestamp not null default current_timestamp,
	
	constraint fk_fact_game
		foreign key (game_id) references dw.dim_game(game_id)
		on update cascade on delete restrict
);

-- Additional indexes

create index if not exists ix_dim_game_platform on dw.dim_game(platform_id);
create index if not exists ix_dim_game_genre on dw.dim_game(genre_id);
create index if not exists ix_dim_game_publisher on dw.dim_game(publisher_id);
