-- Creating Datawarehouse star schema

create schema if not exists dw;

-- 1) Dimensions (lookup)
create table if not exists dw.dim_platform(
	platform_id int generated by default as identity primary key,
	platform text not null unique,
	created_at timestamp not null default current_timestamp
	
);

create table if not exists dw.dim_genre(
	genre_id int generated by default as identity primary key,
	genre text not null unique,
	created_at timestamp not null default current_timestamp
);

create table if not exists dw.dim_publisher(
	publisher_id int generated by default as identity primary key,
	publisher text not null unique,
	created_at timestamp not null default current_timestamp
);

-- 2) Game dimension (main dimension)
-- Grain: 1 row per name, platform and year

create table if not exists dw.dim_game(
	game_id int generated by default as identity primary key,
	game text not null,
	year int null,
	year_key int generated always as (coalesce(year,-1)) stored,
	rank int null,
	
	platform_id int not null,
	genre_id int not null,
	publisher_id int not null,
	
	created_at timestamp not null default current_timestamp,
	
	constraint fk_game_platform
		foreign key (platform_id) references dw.dim_platform(platform_id)
		on update cascade on delete restrict,
		
	constraint fk_game_genre
		foreign key (genre_id) references dw.dim_genre(genre_id)
		on update cascade on delete restrict,
	
	constraint fk_game_publisher
		foreign key (publisher_id) references dw.dim_publisher(publisher_id)
		on update cascade on delete restrict,
		
	constraint uq_game_grain unique (game, platform_id, year_key)
);

-- 3) Fact table

create table if not exists dw.fact_sales(

	game_id int primary key,
	na_sales numeric(10,2) null,
	eu_sales numeric(10,2) null,
	jp_sales numeric(10,2) null,
	other_sales numeric(10,2) null,
	global_sales numeric(10,2) null,
	
	created_at timestamp not null default current_timestamp,
	
	constraint fk_fact_game
		foreign key (game_id) references dw.dim_game(game_id)
		on update cascade on delete restrict,
		
	constraint chk_na_sales_nonnegative check (na_sales is null or na_sales >= 0),
	constraint chk_eu_sales_nonnegative check (eu_sales is null or eu_sales >= 0),
	constraint chk_jp_sales_nonnegative check (jp_sales is null or jp_sales >= 0),
	constraint chk_other_sales_nonnegative check (other_sales is null or other_sales >= 0),
	constraint chk_global_sales_nonnegative check (global_sales is null or global_sales >= 0)
);

-- Additional indexes

create index if not exists ix_dim_game_platform on dw.dim_game(platform_id);
create index if not exists ix_dim_game_genre on dw.dim_game(genre_id);
create index if not exists ix_dim_game_publisher on dw.dim_game(publisher_id);
create index if not exists ix_dim_game_year_key on dw.dim_game(year_key);

/*


 Validating...

SELECT table_schema, table_name
FROM information_schema.tables
WHERE table_schema = 'dw'
ORDER BY table_name;

SELECT indexname, tablename
FROM pg_indexes
WHERE schemaname = 'dw'
ORDER BY tablename, indexname;

SELECT
    tc.table_name,
    tc.constraint_name,
    tc.constraint_type
FROM information_schema.table_constraints tc
WHERE tc.table_schema = 'dw'
ORDER BY tc.table_name, tc.constraint_type;

 */